logLevel: debug

operator:
  image:
    registry: "local"
    repository: netbirdio-operator
    pullPolicy: IfNotPresent
    tag: dev

ingress:
  enabled: false
  allowAutomaticPolicyCreation: true
  kubernetesAPI:
    enabled: false
  router:
    enabled: false
